SET SERVEROUTPUT ON
PROMPT ============================================
PROMPT BASE DE DATOS JEURUS - ORACLE 10G SQL*PLUS
PROMPT ============================================

BEGIN
    EXECUTE IMMEDIATE 'DROP VIEW VW_REPORTE_TICKETS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE COMENTARIO CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE TICKET CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE USUARIO CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CATEGORIA CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PRIORIDAD CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ESTADO CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ROL CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_ROL';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_USUARIO';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CATEGORIA';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PRIORIDAD';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_ESTADO';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TICKET';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_COMENTARIO';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE ROL (
    ID_ROL NUMBER NOT NULL,
    NOMBRE_ROL VARCHAR2(30) NOT NULL,
    CONSTRAINT PK_ROL PRIMARY KEY (ID_ROL),
    CONSTRAINT UK_ROL_NOMBRE UNIQUE (NOMBRE_ROL)
);

CREATE TABLE USUARIO (
    ID_USUARIO NUMBER NOT NULL,
    NOMBRE VARCHAR2(100) NOT NULL,
    CORREO VARCHAR2(120),
    USUARIO VARCHAR2(50) NOT NULL,
    CLAVE VARCHAR2(50) NOT NULL,
    ID_ROL NUMBER NOT NULL,
    CONSTRAINT PK_USUARIO PRIMARY KEY (ID_USUARIO),
    CONSTRAINT UK_USUARIO UNIQUE (USUARIO),
    CONSTRAINT FK_USUARIO_ROL FOREIGN KEY (ID_ROL) REFERENCES ROL(ID_ROL)
);

CREATE TABLE CATEGORIA (
    ID_CATEGORIA NUMBER NOT NULL,
    NOMBRE_CATEGORIA VARCHAR2(80) NOT NULL,
    DESCRIPCION VARCHAR2(300),
    CONSTRAINT PK_CATEGORIA PRIMARY KEY (ID_CATEGORIA),
    CONSTRAINT UK_CATEGORIA UNIQUE (NOMBRE_CATEGORIA)
);

CREATE TABLE PRIORIDAD (
    ID_PRIORIDAD NUMBER NOT NULL,
    NOMBRE_PRIORIDAD VARCHAR2(30) NOT NULL,
    CONSTRAINT PK_PRIORIDAD PRIMARY KEY (ID_PRIORIDAD),
    CONSTRAINT UK_PRIORIDAD UNIQUE (NOMBRE_PRIORIDAD)
);

CREATE TABLE ESTADO (
    ID_ESTADO NUMBER NOT NULL,
    NOMBRE_ESTADO VARCHAR2(30) NOT NULL,
    CONSTRAINT PK_ESTADO PRIMARY KEY (ID_ESTADO),
    CONSTRAINT UK_ESTADO UNIQUE (NOMBRE_ESTADO)
);

CREATE TABLE TICKET (
    ID_TICKET NUMBER NOT NULL,
    TITULO VARCHAR2(150) NOT NULL,
    DESCRIPCION VARCHAR2(2000) NOT NULL,
    FECHA_CREACION DATE DEFAULT SYSDATE NOT NULL,
    FECHA_CIERRE DATE,
    ID_CLIENTE NUMBER NOT NULL,
    ID_AGENTE NUMBER,
    ID_CATEGORIA NUMBER NOT NULL,
    ID_PRIORIDAD NUMBER NOT NULL,
    ID_ESTADO NUMBER NOT NULL,
    CONSTRAINT PK_TICKET PRIMARY KEY (ID_TICKET),
    CONSTRAINT FK_TICKET_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES USUARIO(ID_USUARIO),
    CONSTRAINT FK_TICKET_AGENTE FOREIGN KEY (ID_AGENTE) REFERENCES USUARIO(ID_USUARIO),
    CONSTRAINT FK_TICKET_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA),
    CONSTRAINT FK_TICKET_PRIORIDAD FOREIGN KEY (ID_PRIORIDAD) REFERENCES PRIORIDAD(ID_PRIORIDAD),
    CONSTRAINT FK_TICKET_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO(ID_ESTADO)
);

CREATE TABLE COMENTARIO (
    ID_COMENTARIO NUMBER NOT NULL,
    ID_TICKET NUMBER NOT NULL,
    ID_USUARIO NUMBER NOT NULL,
    MENSAJE VARCHAR2(2000) NOT NULL,
    FECHA_COMENTARIO DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_COMENTARIO PRIMARY KEY (ID_COMENTARIO),
    CONSTRAINT FK_COMENTARIO_TICKET FOREIGN KEY (ID_TICKET) REFERENCES TICKET(ID_TICKET),
    CONSTRAINT FK_COMENTARIO_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE SEQUENCE SEQ_ROL START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_USUARIO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CATEGORIA START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PRIORIDAD START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ESTADO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_TICKET START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_COMENTARIO START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE OR REPLACE TRIGGER TRG_ROL_BI
BEFORE INSERT ON ROL
FOR EACH ROW
BEGIN
    IF :NEW.ID_ROL IS NULL THEN
        SELECT SEQ_ROL.NEXTVAL INTO :NEW.ID_ROL FROM DUAL;
    END IF;
END;
/
SHOW ERRORS

CREATE OR REPLACE TRIGGER TRG_USUARIO_BI
BEFORE INSERT ON USUARIO
FOR EACH ROW
BEGIN
    IF :NEW.ID_USUARIO IS NULL THEN
        SELECT SEQ_USUARIO.NEXTVAL INTO :NEW.ID_USUARIO FROM DUAL;
    END IF;
END;
/
SHOW ERRORS

CREATE OR REPLACE TRIGGER TRG_CATEGORIA_BI
BEFORE INSERT ON CATEGORIA
FOR EACH ROW
BEGIN
    IF :NEW.ID_CATEGORIA IS NULL THEN
        SELECT SEQ_CATEGORIA.NEXTVAL INTO :NEW.ID_CATEGORIA FROM DUAL;
    END IF;
END;
/
SHOW ERRORS

CREATE OR REPLACE TRIGGER TRG_PRIORIDAD_BI
BEFORE INSERT ON PRIORIDAD
FOR EACH ROW
BEGIN
    IF :NEW.ID_PRIORIDAD IS NULL THEN
        SELECT SEQ_PRIORIDAD.NEXTVAL INTO :NEW.ID_PRIORIDAD FROM DUAL;
    END IF;
END;
/
SHOW ERRORS

CREATE OR REPLACE TRIGGER TRG_ESTADO_BI
BEFORE INSERT ON ESTADO
FOR EACH ROW
BEGIN
    IF :NEW.ID_ESTADO IS NULL THEN
        SELECT SEQ_ESTADO.NEXTVAL INTO :NEW.ID_ESTADO FROM DUAL;
    END IF;
END;
/
SHOW ERRORS

CREATE OR REPLACE TRIGGER TRG_TICKET_BI
BEFORE INSERT ON TICKET
FOR EACH ROW
BEGIN
    IF :NEW.ID_TICKET IS NULL THEN
        SELECT SEQ_TICKET.NEXTVAL INTO :NEW.ID_TICKET FROM DUAL;
    END IF;
END;
/
SHOW ERRORS

CREATE OR REPLACE TRIGGER TRG_COMENTARIO_BI
BEFORE INSERT ON COMENTARIO
FOR EACH ROW
BEGIN
    IF :NEW.ID_COMENTARIO IS NULL THEN
        SELECT SEQ_COMENTARIO.NEXTVAL INTO :NEW.ID_COMENTARIO FROM DUAL;
    END IF;
END;
/
SHOW ERRORS

INSERT INTO ROL(NOMBRE_ROL) VALUES('ADMINISTRADOR');
INSERT INTO ROL(NOMBRE_ROL) VALUES('AGENTE');
INSERT INTO ROL(NOMBRE_ROL) VALUES('CLIENTE');

INSERT INTO PRIORIDAD(NOMBRE_PRIORIDAD) VALUES('BAJA');
INSERT INTO PRIORIDAD(NOMBRE_PRIORIDAD) VALUES('MEDIA');
INSERT INTO PRIORIDAD(NOMBRE_PRIORIDAD) VALUES('ALTA');
INSERT INTO PRIORIDAD(NOMBRE_PRIORIDAD) VALUES('URGENTE');

INSERT INTO ESTADO(NOMBRE_ESTADO) VALUES('ABIERTO');
INSERT INTO ESTADO(NOMBRE_ESTADO) VALUES('EN_PROCESO');
INSERT INTO ESTADO(NOMBRE_ESTADO) VALUES('CERRADO');

INSERT INTO CATEGORIA(NOMBRE_CATEGORIA, DESCRIPCION) VALUES('Software', 'Problemas relacionados con programas o aplicaciones.');
INSERT INTO CATEGORIA(NOMBRE_CATEGORIA, DESCRIPCION) VALUES('Hardware', 'Problemas relacionados con equipos fisicos.');
INSERT INTO CATEGORIA(NOMBRE_CATEGORIA, DESCRIPCION) VALUES('Redes', 'Problemas de internet, red local o conectividad.');
INSERT INTO CATEGORIA(NOMBRE_CATEGORIA, DESCRIPCION) VALUES('Cuenta de usuario', 'Solicitudes relacionadas con acceso y credenciales.');

INSERT INTO USUARIO(NOMBRE, CORREO, USUARIO, CLAVE, ID_ROL)
VALUES('Administrador JEURUS', 'admin@jeurus.com', 'JEURUS', 'JEURUS',
       (SELECT ID_ROL FROM ROL WHERE NOMBRE_ROL = 'ADMINISTRADOR'));

INSERT INTO USUARIO(NOMBRE, CORREO, USUARIO, CLAVE, ID_ROL)
VALUES('Agente de soporte', 'agente@jeurus.com', 'agente', '1234',
       (SELECT ID_ROL FROM ROL WHERE NOMBRE_ROL = 'AGENTE'));

INSERT INTO USUARIO(NOMBRE, CORREO, USUARIO, CLAVE, ID_ROL)
VALUES('Cliente de prueba', 'cliente@jeurus.com', 'cliente', '1234',
       (SELECT ID_ROL FROM ROL WHERE NOMBRE_ROL = 'CLIENTE'));

INSERT INTO TICKET(TITULO, DESCRIPCION, ID_CLIENTE, ID_CATEGORIA, ID_PRIORIDAD, ID_ESTADO)
VALUES('No puedo iniciar sesion', 'El sistema no permite ingresar con mi usuario.',
       (SELECT ID_USUARIO FROM USUARIO WHERE USUARIO = 'cliente'),
       (SELECT ID_CATEGORIA FROM CATEGORIA WHERE NOMBRE_CATEGORIA = 'Cuenta de usuario'),
       (SELECT ID_PRIORIDAD FROM PRIORIDAD WHERE NOMBRE_PRIORIDAD = 'ALTA'),
       (SELECT ID_ESTADO FROM ESTADO WHERE NOMBRE_ESTADO = 'ABIERTO'));

INSERT INTO TICKET(TITULO, DESCRIPCION, ID_CLIENTE, ID_CATEGORIA, ID_PRIORIDAD, ID_ESTADO)
VALUES('Falla de internet', 'El equipo no tiene acceso a internet desde la manana.',
       (SELECT ID_USUARIO FROM USUARIO WHERE USUARIO = 'cliente'),
       (SELECT ID_CATEGORIA FROM CATEGORIA WHERE NOMBRE_CATEGORIA = 'Redes'),
       (SELECT ID_PRIORIDAD FROM PRIORIDAD WHERE NOMBRE_PRIORIDAD = 'URGENTE'),
       (SELECT ID_ESTADO FROM ESTADO WHERE NOMBRE_ESTADO = 'ABIERTO'));

INSERT INTO COMENTARIO(ID_TICKET, ID_USUARIO, MENSAJE)
VALUES((SELECT MIN(ID_TICKET) FROM TICKET),
       (SELECT ID_USUARIO FROM USUARIO WHERE USUARIO = 'cliente'),
       'Solicito ayuda para recuperar el acceso.');

CREATE OR REPLACE VIEW VW_REPORTE_TICKETS AS
SELECT
    T.ID_TICKET,
    T.TITULO,
    T.DESCRIPCION,
    C.NOMBRE_CATEGORIA AS CATEGORIA,
    P.NOMBRE_PRIORIDAD AS PRIORIDAD,
    E.NOMBRE_ESTADO AS ESTADO,
    CLI.NOMBRE AS CLIENTE,
    NVL(AGE.NOMBRE, 'SIN ASIGNAR') AS AGENTE,
    TO_CHAR(T.FECHA_CREACION, 'DD/MM/YYYY HH24:MI') AS FECHA_CREACION,
    NVL(TO_CHAR(T.FECHA_CIERRE, 'DD/MM/YYYY HH24:MI'), 'PENDIENTE') AS FECHA_CIERRE,
    (SELECT COUNT(*) FROM COMENTARIO CO WHERE CO.ID_TICKET = T.ID_TICKET) AS TOTAL_COMENTARIOS
FROM TICKET T
INNER JOIN CATEGORIA C ON T.ID_CATEGORIA = C.ID_CATEGORIA
INNER JOIN PRIORIDAD P ON T.ID_PRIORIDAD = P.ID_PRIORIDAD
INNER JOIN ESTADO E ON T.ID_ESTADO = E.ID_ESTADO
INNER JOIN USUARIO CLI ON T.ID_CLIENTE = CLI.ID_USUARIO
LEFT JOIN USUARIO AGE ON T.ID_AGENTE = AGE.ID_USUARIO;

COMMIT;

PROMPT ============================================
PROMPT OBJETOS CREADOS CORRECTAMENTE
PROMPT Usuarios de prueba:
PROMPT JEURUS / JEURUS     Rol ADMINISTRADOR
PROMPT agente / 1234       Rol AGENTE
PROMPT cliente / 1234      Rol CLIENTE
PROMPT ============================================

SELECT * FROM VW_REPORTE_TICKETS;
